#!/bin/bash

TESTS=5

if [ $1 = "all" ]
then
	
	for i in `echo spl/*.spl`;
	do
		
		echo "Running test: $i"

		bin/river $i $2 < ${i%.*}.input

	done

else

	if [[ $1 != *[!0-9]* ]]; then

    	bin/river spl/p$1.spl $2 < spl/p$1.input
	
	else
    
		bin/river spl/$1.spl $2 < spl/$1.input

	fi

fi