#!/bin/bash

TESTS=5

if [ $1 = "all" ]
then
	
	for i in $(seq 1 $TESTS);
	do
		
		echo "Running problem $i"

		bin/river spl/p$i.spl $2 < spl/p$i.input

	done

else

	if [[ $1 != *[!0-9]* ]]; then

    	bin/river spl/p$1.spl $2 < spl/p$1.input
	
	else
    
		bin/river spl/$1.spl $2 < spl/$1.input

	fi

fi